[package]
name = "jwtvoting"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.85.0", directory="noir-projects/aztec-nr/aztec" }
jwt = { tag = "v0.5.0", git = "https://github.com/zkemail/noir-jwt" }